@Library('Shared') _
pipeline{
 agent any
 parameters{
	string(name: "FRONTEND_DOCKER_TAG", defaultValue: "", description : "frontend docker tag build by docker tag")
	string(name: "BACKEND_DOCKER_TAG", defaultValue: "", description: "backend docker tag build by dooker tag")
 }
 stages{
 	stage("workspace clean up"){
		steps{
			script{
				cleanWs()
			}
		}	
	}
        stage("git: code checkout"){
                steps{
                        script{
				code_checkout("https://github.com/Vinayak-100ni/jenkins-CI-CD.git","main")
                        }
                }
        }
        stage("verify: docker image"){
                steps{
                        script{
				echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
				echo "BAECKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                        }
                }
        }
        stage("update: k8s manifests"){
                steps{
                        script{
				dir('kubernetes'){
					sh """
						sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}/g backend.yaml
					"""
				}

                        }
                                dir('kubernetes'){
                                        sh """
                                                sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}/g frontend.yaml
                                        """
                                }

                        }
                }
        }
        stage("git : code upate and push to github "){
                steps{
                        script{
                        	withCredentials([gitUsernamePassword(credentialsId: 'Github-cred' , gitToolName: 'Default')]){
				 sh '''
				 echo "Checking repository status: "
                        	 git status
                    
                        	 echo "Adding changes to git: "
                        	 git add .
                        
                       		 echo "Commiting changes: "
                        	 git commit -m "Updated environment variables"
                        
                        	 echo "Pushing changes to github: "
                       		 git push https://github.com/LondheShubham153/Wanderlust-Mega-Project.git main
				 '''
				}
                        }
                }
        }
 }
 post {
        success {
            script {
                emailext attachLog: true,
                from: 'trainwithshubham@gmail.com',
                subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'trainwithshubham@gmail.com',
            mimeType: 'text/html'
            }
        }
      failure {
            script {
                emailext attachLog: true,
                from: 'trainwithshubham@gmail.com',
                subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'trainwithshubham@gmail.com',
            mimeType: 'text/html'
            }
        }
 }
}
